package com.salilvnair.intellij.plugin.daakia.ui.core.event.type;

/**
 * @author Salil V Nair
 */
public enum DaakiaEventType {
    ON_CLICK_ADD_HEADER,
    ON_CLICK_SEND,
    ON_CLICK_SAVE,
    ON_CLICK_DELETE_HEADER_ROW,
    AFTER_REST_EXCHANGE,
    ON_RECEIVING_RESPONSE,
    ON_AFTER_HISTORY_ADDED,
    ON_SELECT_HISTORY_DATA_NODE,
    ON_LOAD_SELECTED_HISTORY_DATA,
    ON_LOAD_SELECTED_STORE_COLLECTION_DATA,
    ON_DBL_CLICK_HISTORY_DATA_NODE,
    ON_RIGHT_CLICK_RENAME_HISTORY_NODE,
    ON_RIGHT_CLICK_RENAME_STORE_COLLECTION_NODE,
    ON_SELECT_STORE_COLLECTION_NODE,
    ON_DBL_CLICK_STORE_COLLECTION_NODE,
    ON_CLICK_ADD_NEW_COLLECTION,
    ON_CLICK_DELETE_COLLECTIONS,
    ON_CLICK_SIDE_NAV_VISIBILITY_TOGGLER,
    ON_CLICK_REQUEST_BODY_FORMATTER_BTN,
    ON_CLICK_RESPONSE_BODY_FORMATTER_BTN,
}
