package com.salilvnair.intellij.plugin.daakia.ui.service.type;

public enum AppDaakiaType implements DaakiaTypeBase {
    INIT_HISTORY,
    ADD_HISTORY,
    ON_CLICK_HISTORY_NODE,
    ON_DBL_CLICK_HISTORY_NODE,
    ON_DBL_CLICK_STORE_COLLECTION_NODE,
    ON_RIGHT_CLICK_RENAME_HISTORY_NODE,
    ON_RIGHT_CLICK_RENAME_STORE_COLLECTION_NODE,
    ON_CLICK_STORE_COLLECTION_NODE,
    CREATE_REQUEST_HEADER,
    INIT_STORE_COLLECTIONS,
    UPDATE_STORE_COLLECTION_NODE,
    CREATE_RESPONSE_HEADERS,
    CREATE_RESPONSE_STATUS,
}
